config/routes.rb
Rails.application.routes.draw do
  resources :extractors
  root "extractors#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/extractor.rb
class Extractor < ApplicationRecord
  has_many_attached :files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/extractors_controller.rb
class ExtractorsController < ApplicationController
  before_action :set_extractor, only: [:show, :edit, :update, :destroy]

  # GET /extractors
  # GET /extractors.json
  def index
    @extractors = Extractor.all
  end

  # GET /extractors/1
  # GET /extractors/1.json
  def show
  end

  # GET /extractors/new
  def new
    @extractor = Extractor.new
  end

  # GET /extractors/1/edit
  def edit
  end

  # POST /extractors
  # POST /extractors.json
  def create
    @extractor = Extractor.new(extractor_params)

    respond_to do |format|
      if @extractor.save
        format.html { redirect_to @extractor, notice: 'Extractor was successfully created.' }
        format.json { render :show, status: :created, location: @extractor }
      else
        format.html { render :new }
        format.json { render json: @extractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extractors/1
  # PATCH/PUT /extractors/1.json
  def update
    respond_to do |format|
      if @extractor.update(extractor_params)
        format.html { redirect_to @extractor, notice: 'Extractor was successfully updated.' }
        format.json { render :show, status: :ok, location: @extractor }
      else
        format.html { render :edit }
        format.json { render json: @extractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extractors/1
  # DELETE /extractors/1.json
  def destroy
    @extractor.destroy
    respond_to do |format|
      format.html { redirect_to extractors_url, notice: 'Extractor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extractor
      @extractor = Extractor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def extractor_params
      params.require(:extractor).permit(:title, :description, :is_extracted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extractors_helper.rb
module ExtractorsHelper
end

app/views/extractors/_form.html.erb
<%= form_for @extractor, :html => { :class => "form-horizontal extractor" } do |f| %>

  <% if @extractor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@extractor.errors.count, "error") %> prohibited this extractor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @extractor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :is_extracted, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :is_extracted, :class => 'form-control' %>
    </div>
    <%=f.error_span(:is_extracted) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                extractors_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/extractors/edit.html.erb
<%- model_class = Extractor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/extractors/index.html.erb
<%- model_class = Extractor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:is_extracted) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @extractors.each do |extractor| %>
      <tr>
        <td><%= link_to extractor.id, extractor_path(extractor) %></td>
        <td><%= extractor.title %></td>
        <td><%= extractor.description %></td>
        <td><%= extractor.is_extracted %></td>
        <td><%=l extractor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_extractor_path(extractor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      extractor_path(extractor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_extractor_path,
            :class => 'btn btn-primary' %>

app/views/extractors/new.html.erb
<%- model_class = Extractor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/extractors/show.html.erb
<%- model_class = Extractor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @extractor.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @extractor.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_extracted) %>:</strong></dt>
  <dd><%= @extractor.is_extracted %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              extractors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_extractor_path(@extractor), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              extractor_path(@extractor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ZipExtractor" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ZipExtractor</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2020</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>